
title: My Resume
url: 'https://kiki86151.github.io'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Carson Wang
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: kiki86151@hotmail.com
#phone: 012 345 6789
website: kiki86151.github.io #do not add http://
linkedin: carson321
github: kiki86151
#twitter: '@webjeda'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
